name: graph_attribution
channels:
- rdkit
dependencies:
- pip
- python=3.7
- rdkit
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- scipy
- seaborn
- tqdm
- scikit-learn
- networkx
- pip:
        - tensorflow
        - git+https://github.com/deepmind/sonnet.git
        - graph_nets
        - more-itertools
        - ml-collections
